import type { Client, Driver, Order, Address, Origin } from './types';

export const clients: Client[] = [
  { id: '1', nome: 'Ana Costa', telefone: '+5531999998888', createdAt: new Date() },
  { id: '2', nome: 'Bruno Lima', telefone: '+5511988887777', createdAt: new Date() },
  { id: '3', nome: 'Carla Dias', telefone: '+5521977776666', createdAt: new Date() },
  { id: '4', nome: 'Daniel Alves', telefone: '+5541966665555', createdAt: new Date() },
  { id: '5', nome: 'Eduarda Martins', telefone: '+5551955554444', createdAt: new Date() },
];

export const addresses: Address[] = [
    { id: '1', clientId: '1', label: 'Casa', fullAddress: 'Rua A, 123, Belo Horizonte, MG', logradouro: 'Rua A', numero: '123', bairro: 'Centro', cidade: 'Belo Horizonte', estado: 'MG', cep: '30130-000' },
    { id: '2', clientId: '1', label: 'Trabalho', fullAddress: 'Av. B, 456, Contagem, MG', logradouro: 'Av. B', numero: '456', bairro: 'Industrial', cidade: 'Contagem', estado: 'MG', cep: '32220-000' },
    { id: '3', clientId: '2', label: 'Casa', fullAddress: 'Rua C, 789, São Paulo, SP', logradouro: 'Rua C', numero: '789', bairro: 'Pinheiros', cidade: 'São Paulo', estado: 'SP', cep: '05404-000' },
];

export const drivers: Driver[] = [
  {
    id: '1',
    nome: 'João Silva',
    telefone: '+5511987654321',
    placa: 'ABC-1234',
    ativo: true,
    companyId: '1',
  },
  {
    id: '2',
    nome: 'Maria Souza',
    telefone: '+5521912345678',
    placa: 'XYZ-5678',
    ativo: true,
    companyId: '1',
  },
];

export const orders: Order[] = [
  {
    id: '1',
    codigoRastreio: 'TR-ABC123',
    nomeCliente: 'Ana Costa',
    telefone: '+5531999998888',
    origem: 'Rua Principal, 1000, Centro, São Paulo - SP, 01000-000',
    destino: 'Av. B, 456, Contagem',
    valorEntrega: 25.5,
    formaPagamento: 'pix',
    pago: true,
    status: 'ENTREGUE',
    motoristaId: '1',
    timeline: [
      { status: 'PENDENTE', at: new Date('2024-07-28T10:00:00Z'), userId: 'admin' },
      { status: 'EM_ROTA', at: new Date('2024-07-28T11:30:00Z'), userId: 'admin' },
      { status: 'ENTREGUE', at: new Date('2024-07-28T14:00:00Z'), userId: 'admin' },
    ],
    messages: [],
    createdAt: new Date('2024-07-28T10:00:00Z'),
    createdBy: 'admin',
    companyId: '1',
  },
  {
    id: '2',
    codigoRastreio: 'TR-DEF456',
    nomeCliente: 'Bruno Lima',
    telefone: '+5511988887777',
    origem: 'Avenida Brasil, 500, Rio de Janeiro - RJ, 20940-000',
    destino: 'Paulista, São Paulo',
    valorEntrega: 18.0,
    formaPagamento: 'dinheiro',
    pago: false,
    status: 'EM_ROTA',
    motoristaId: '2',
    timeline: [
        { status: 'PENDENTE', at: new Date('2024-07-29T09:00:00Z'), userId: 'admin' },
        { status: 'EM_ROTA', at: new Date('2024-07-29T10:15:00Z'), userId: 'admin' },
    ],
    messages: [],
    createdAt: new Date('2024-07-29T09:00:00Z'),
    createdBy: 'admin',
    companyId: '1',
  },
  {
    id: '3',
    codigoRastreio: 'TR-GHI789',
    nomeCliente: 'Carla Dias',
    telefone: '+5521977776666',
    origem: 'Rua Principal, 1000, Centro, São Paulo - SP, 01000-000',
    destino: 'Barra da Tijuca, Rio de Janeiro',
    valorEntrega: 45.0,
    formaPagamento: 'cartao',
    pago: true,
    status: 'PENDENTE',
    timeline: [
        { status: 'PENDENTE', at: new Date(), userId: 'admin' }
    ],
    messages: [],
    createdAt: new Date(),
    createdBy: 'admin',
    companyId: '1',
  },
  {
    id: '4',
    codigoRastreio: 'TR-JKL012',
    nomeCliente: 'Daniel Alves',
    telefone: '+5541966665555',
    origem: 'Avenida Brasil, 500, Rio de Janeiro - RJ, 20940-000',
    destino: 'Batel, Curitiba',
    valorEntrega: 22.0,
    formaPagamento: 'link',
    pago: false,
    status: 'PENDENTE',
    timeline: [
        { status: 'PENDENTE', at: new Date(), userId: 'admin' }
    ],
    messages: [],
    createdAt: new Date(),
    createdBy: 'admin',
    companyId: '1',
  },
  {
    id: '5',
    codigoRastreio: 'TR-MNO345',
    nomeCliente: 'Eduarda Martins',
    telefone: '+5551955554444',
    origem: 'Rua Principal, 1000, Centro, São Paulo - SP, 01000-000',
    destino: 'Centro Histórico, Porto Alegre',
    valorEntrega: 15.75,
    formaPagamento: 'pix',
    pago: true,
    status: 'ENTREGUE',
    motoristaId: '1',
    timeline: [
      { status: 'PENDENTE', at: new Date('2024-07-27T13:00:00Z'), userId: 'admin' },
      { status: 'EM_ROTA', at: new Date('2024-07-27T14:00:00Z'), userId: 'admin' },
      { status: 'ENTREGUE', at: new Date('2024-07-27T15:30:00Z'), userId: 'admin' },
    ],
    messages: [],
    createdAt: new Date('2024-07-27T13:00:00Z'),
    createdBy: 'admin',
    companyId: '1',
  },
  {
    id: '6',
    codigoRastreio: 'TR-PQR678',
    nomeCliente: 'Fábio Rocha',
    telefone: '+5561944443333',
    origem: 'Rua Principal, 1000, Centro, São Paulo - SP, 01000-000',
    destino: 'Asa Norte, Brasília',
    valorEntrega: 30.0,
    formaPagamento: 'boleto',
    pago: false,
    status: 'CANCELADA',
    timeline: [
        { status: 'PENDENTE', at: new Date('2024-07-26T10:00:00Z'), userId: 'admin' },
        { status: 'CANCELADA', at: new Date('2024-07-26T11:00:00Z'), userId: 'admin' },
    ],
    observacao: 'Cliente cancelou o pedido.',
    messages: [],
    createdAt: new Date('2024-07-26T10:00:00Z'),
    createdBy: 'admin',
    companyId: '1',
  },
  {
    id: '7',
    codigoRastreio: 'TR-STU901',
    nomeCliente: 'Gabriela Nogueira',
    telefone: '+5571933332222',
    origem: 'Avenida Brasil, 500, Rio de Janeiro - RJ, 20940-000',
    destino: 'Rio Vermelho, Salvador',
    valorEntrega: 28.5,
    formaPagamento: 'dinheiro',
    pago: false,
    status: 'EM_ROTA',
    motoristaId: '2',
    timeline: [
        { status: 'PENDENTE', at: new Date(), userId: 'admin' },
        { status: 'EM_ROTA', at: new Date(), userId: 'admin' },
    ],
    messages: [],
    createdAt: new Date(),
    createdBy: 'admin',
    companyId: '1',
  },
  {
    id: '8',
    codigoRastreio: 'TR-VWX234',
    nomeCliente: 'Heitor Santos',
    telefone: '+5581922221111',
    origem: 'Rua Principal, 1000, Centro, São Paulo - SP, 01000-000',
    destino: 'Recife Antigo, Recife',
    valorEntrega: 35.2,
    formaPagamento: 'cartao',
    pago: true,
    status: 'PENDENTE',
    timeline: [
        { status: 'PENDENTE', at: new Date(), userId: 'admin' }
    ],
    messages: [],
    createdAt: new Date(),
    createdBy: 'admin',
    companyId: '1',
  },
  {
    id: '9',
    codigoRastreio: 'TR-YZA567',
    nomeCliente: 'Isabela Ferreira',
    telefone: '+5585911110000',
    origem: 'Avenida Brasil, 500, Rio de Janeiro - RJ, 20940-000',
    destino: 'Praia de Iracema, Fortaleza',
    valorEntrega: 19.9,
    formaPagamento: 'pix',
    pago: false,
    status: 'PENDENTE',
    timeline: [
        { status: 'PENDENTE', at: new Date(), userId: 'admin' }
    ],
    messages: [],
    createdAt: new Date(),
    createdBy: 'admin',
    companyId: '1',
  },
  {
    id: '10',
    codigoRastreio: 'TR-BCD890',
    nomeCliente: 'Juliano Pereira',
    telefone: '+5592900009999',
    origem: 'Rua Principal, 1000, Centro, São Paulo - SP, 01000-000',
    destino: 'Ponta Negra, Manaus',
    valorEntrega: 55.0,
    formaPagamento: 'link',
    pago: true,
    status: 'ENTREGUE',
    motoristaId: '1',
    timeline: [
        { status: 'PENDENTE', at: new Date('2024-07-28T16:00:00Z'), userId: 'admin' },
        { status: 'EM_ROTA', at: new Date('2024-07-28T17:00:00Z'), userId: 'admin' },
        { status: 'ENTREGUE', at: new Date('2024-07-28T19:30:00Z'), userId: 'admin' },
    ],
    messages: [],
    createdAt: new Date('2024-07-28T16:00:00Z'),
    createdBy: 'admin',
    companyId: '1',
  },
];
